# Original chart: https://github.com/k8s-at-home/charts/tree/master/charts/stable/home-assistant

image:
  repository: homeassistant/home-assistant
  pullPolicy: IfNotPresent
  tag: 2021.11.5

replicaCount: 1
maxSurge: 1
maxUnavailable: 0

revisionHistoryLimit: 0

strategy:
  type: Recreate

service:
  main:
    ports:
      http:
        port: 8123
    type: LoadBalancer
    loadBalancerIP: 192.168.20.221
    annotations:
      metallb.universe.tf/address-pool: default
      metallb.universe.tf/allow-shared-ip: homeassistant-svc

ingress:
  main:
    enabled: false

persistence:
  config:
    enabled: true
    emptyDir: false
    storageClassName: longhorn
    accessMode: ReadWriteOnce
    size: 2Gi
    skipuninstall: true
    existingClaim: homeassistant-pvc