apiVersion: v1
kind: Service
metadata:  
  name: uptime-kuma-svc
  namespace: uptime-kuma
spec:
  selector:    
    component: uptime-kuma
  type: LoadBalancer
  loadBalancerIP: 192.168.20.225
  ports:  
  - name: http
    port: 3001
    targetPort: 3001
    protocol: TCP
